name: Build XNU

on:
  workflow_dispatch:
  push:

jobs:
  ssh:
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build XNU
      run: |
        git clone https://github.com/apple/darwin-xnu xnu
        cd xnu
        make SDKROOT=macosx.internal
